info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
  /user/create-user:
    get:
      parameters:
      - description: 用户名称
        in: query
        maxLength: 100
        name: name
        type: string
      - description: 密码
        in: query
        maxLength: 100
        name: password
        type: string
      - description: 密码
        in: query
        maxLength: 100
        name: passwordv2
        type: string
      responses:
        "200":
          description: code","userList"}
          schema:
            type: string
      summary: 创建用户
  /user/delete-user:
    delete:
      parameters:
      - description: 用户id
        in: query
        maxLength: 100
        name: id
        required: true
        type: string
      responses:
        "200":
          description: code","userList"}
          schema:
            type: string
      summary: 删除用户
  /user/get-all-user:
    get:
      responses:
        "200":
          description: code","userList"}
          schema:
            type: string
      summary: 获取所有用户
  /user/get-user-by-name:
    get:
      parameters:
      - description: 用户名称
        in: query
        maxLength: 100
        name: name
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 根据用户名获取用户
  /user/update-user:
    put:
      parameters:
      - description: 用户id
        in: formData
        maxLength: 100
        name: id
        required: true
        type: string
      - description: 用户名称
        in: formData
        maxLength: 100
        name: name
        required: true
        type: string
      - description: 用户密码
        in: formData
        maxLength: 100
        name: password
        required: true
        type: string
      - description: 用户手机号
        in: formData
        maxLength: 100
        name: phone
        required: true
        type: string
      responses:
        "200":
          description: code","userList"}
          schema:
            type: string
      summary: 修改用户
swagger: "2.0"
